[package]
name = "sftp_upload"
version = "0.1.0"
authors = ["olli"]
edition = "2018"

[profile.release]
opt-level = 3
debug = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "*"
